server:
  port: 8082
spring:
  main:
    web-application-type: none
  shell:
    command:
      clear:
        enabled: true
    interactive:
      enabled: true
#logging:
#  level:
#    org:
#      jline: debug
#    root: debug